In [4]:
import pandas as pd

# 1. Definís la ruta relativa de tu archivo
# (Asegurate de estar ejecutando la celda en el mismo nivel que tu archivo tpe.ipynb)
ruta_archivo = "listings (1).csv.gz"

# 2. Leés el archivo CSV comprimido directamente.
# El parámetro compression='gzip' suele ser detectado automáticamente, 
# pero siempre es buena práctica explicitarlo.
# low_memory=False ayuda a evitar advertencias si hay columnas con tipos de datos mixtos.
df_listings = pd.read_csv(ruta_archivo, compression='gzip', low_memory=False)

# 3. Exploración inicial: ver la dimensión de la tabla y las primeras filas
print(f"Dimensiones del dataset: {df_listings.shape}")
df_listings.head()

Dimensiones del dataset: (29685, 90)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,54019695,https://www.airbnb.com/rooms/54019695,20260629030533,2026-07-02,city scrape,Hermoso departamento con piscina en Puerto Mad...,Enjoy a stylish experience in this centrally-l...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,298874610,...,NaN,NaN,NaN,NaN,NaN,24,24,0,0,NaN
1,41720307,https://www.airbnb.com/rooms/41720307,20260629030533,2026-06-29,city scrape,"Departamento dos ambientes, 2cuadras recoleta ...",Brand new remodeled apartment 2 blocks from th...,NaN,https://a0.muscache.com/pictures/37e687e2-2587...,220409424,...,4.67,4.67,4.56,NaN,NaN,8,8,0,0,0.16
2,1090530711732696379,https://www.airbnb.com/rooms/1090530711732696379,20260629030533,2026-07-02,previous scrape,"alquiler mensual ,escenografico.",This place is strategically located - it will ...,NaN,https://a0.muscache.com/pictures/3adbe27a-af59...,488443857,...,4.67,5.00,4.67,NaN,NaN,3,1,2,0,0.34
3,1482653002662185299,https://www.airbnb.com/rooms/1482653002662185299,20260629030533,2026-07-02,city scrape,Descanso ideal - Av. Sante Fe,"Large and comfortable apartment for 4 people, ...",NaN,https://a0.muscache.com/pictures/hosting/Hosti...,283840529,...,4.95,4.89,4.89,NaN,NaN,12,12,0,0,1.78
4,1046394538968941382,https://www.airbnb.com/rooms/1046394538968941382,20260629030533,2026-06-29,city scrape,Excelente zona,Enjoy easy access to everything from this perf...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,550970409,...,NaN,NaN,NaN,NaN,NaN,1,0,1,0,NaN

In [5]:
df_listings.info()

<class 'pandas.DataFrame'>
RangeIndex: 29685 entries, 0 to 29684
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            29685 non-null  int64
 1   listing_url                                   29685 non-null  str
 2   scrape_id                                     29685 non-null  int64
 3   last_scraped                                  29685 non-null  str
 4   source                                        29685 non-null  str
 5   name                                          29685 non-null  str
 6   description                                   28917 non-null  str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   29684 non-null  str
 9   host_id                                       29685 non-null  int64
 10  host_url                                      29685 non-null  str
 11  host_profile_id                               29685 non-null  int64
 12  host_profile_url                              29685 non-null  str
 13  host_name                                     29685 non-null  str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      29685 non-null  int64
 16  hosts_time_as_user_months                     29685 non-null  int64
 17  hosts_time_as_host_years                      29685 non-null  int64
 18  hosts_time_as_host_months                     29685 non-null  int64
 19  host_location                                 23105 non-null  str
 20  host_about                                    16747 non-null  str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             29685 non-null  str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              29685 non-null  str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           29685 non-null  int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          29685 non-null  str
 32  host_identity_verified                        29685 non-null  str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        29685 non-null  str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      29685 non-null  float64
 37  longitude                                     29685 non-null  float64
 38  property_type                                 29685 non-null  str
 39  room_type                                     29685 non-null  str
 40  accommodates                                  29685 non-null  int64
 41  bathrooms                                     26244 non-null  float64
 42  bathrooms_text                                29659 non-null  str
 43  bedrooms                                      24500 non-null  float64
 44  beds                                          27102 non-null  float64
 45  amenities                                     29685 non-null  str
 46  price                                         27893 non-null  str
 47  price_quote_checkin_date                      28347 non-null  str
 48  price_quote_checkout_date                     28347 non-null  str
 49  price_quote_total_price                       27893 non-null  float64
 50  price_quote_price_per_night                   27893 non-null  float64
 51  price_quote_raw                               28347 non-null  str
 52  minimum_nights                                29682 non-null  float64
 53  maximum_nights                                29682 non-null  float64
 54  minimum_minimum_nights                        29682 non-null  float64
 55  maximum_minimum_nights                        29682 non-null  float64
 56  minimum_maximum_nights                        29682 non-null  float64
 57  maximum_maximum_nights                        29682 non-null  float64
 58  minimum_nights_avg_ntm                        29685 non-null  float64
 59  maximum_nights_avg_ntm                        29685 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29490 non-null  str
 62  availability_30                               29685 non-null  int64
 63  availability_60                               29685 non-null  int64
 64  availability_90                               29685 non-null  int64
 65  availability_365                              29685 non-null  int64
 66  calendar_last_scraped                         29685 non-null  str
 67  number_of_reviews                             29685 non-null  int64
 68  number_of_reviews_ltm                         29685 non-null  int64
 69  number_of_reviews_l30d                        29685 non-null  int64
 70  availability_eoy                              29685 non-null  int64
 71  number_of_reviews_ly                          29685 non-null  int64
 72  estimated_occupancy_l365d                     29685 non-null  int64
 73  estimated_revenue_l365d                       27888 non-null  float64
 74  first_review                                  25957 non-null  str
 75  last_review                                   25957 non-null  str
 76  review_scores_rating                          25957 non-null  float64
 77  review_scores_accuracy                        25957 non-null  float64
 78  review_scores_cleanliness                     25957 non-null  float64
 79  review_scores_checkin                         25957 non-null  float64
 80  review_scores_communication                   25957 non-null  float64
 81  review_scores_location                        25957 non-null  float64
 82  review_scores_value                           25957 non-null  float64
 83  license                                       486 non-null    str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                29685 non-null  int64
 86  calculated_host_listings_count_entire_homes   29685 non-null  int64
 87  calculated_host_listings_count_private_rooms  29685 non-null  int64
 88  calculated_host_listings_count_shared_rooms   29685 non-null  int64
 89  reviews_per_month                             25957 non-null  float64
dtypes: float64(37), int64(24), str(29)
memory usage: 20.4 MB

                         Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   id                                            29685 non-null  int64  
 1   listing_url                                   29685 non-null  str    
 2   scrape_id                                     29685 non-null  int64  
 3   last_scraped                                  29685 non-null  str    
 4   source                                        29685 non-null  str    
 5   name                                          29685 non-null  str    
 6   description                                   28917 non-null  str    
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   29684 non-null  str    
 9   host_id                                       29685 non-null  int64  
 10  host_url                                      29685 non-null  str    
 11  host_profile_id                               29685 non-null  int64  
 12  host_profile_url                              29685 non-null  str    
 13  host_name                                     29685 non-null  str    
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      29685 non-null  int64  
 16  hosts_time_as_user_months                     29685 non-null  int64  
 17  hosts_time_as_host_years                      29685 non-null  int64  
 18  hosts_time_as_host_months                     29685 non-null  int64  
 19  host_location                                 23105 non-null  str    
 20  host_about                                    16747 non-null  str    
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             29685 non-null  str    
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              29685 non-null  str    
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           29685 non-null  int64  
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          29685 non-null  str    
 32  host_identity_verified                        29685 non-null  str    
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        29685 non-null  str    
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      29685 non-null  float64
 37  longitude                                     29685 non-null  float64
 38  property_type                                 29685 non-null  str    
 39  room_type                                     29685 non-null  str    
 40  accommodates                                  29685 non-null  int64  
 41  bathrooms                                     26244 non-null  float64
 42  bathrooms_text                                29659 non-null  str    
 43  bedrooms                                      24500 non-null  float64
 44  beds                                          27102 non-null  float64
 45  amenities                                     29685 non-null  str    
 46  price                                         27893 non-null  str    
 47  price_quote_checkin_date                      28347 non-null  str    
 48  price_quote_checkout_date                     28347 non-null  str    
 49  price_quote_total_price                       27893 non-null  float64
 50  price_quote_price_per_night                   27893 non-null  float64
 51  price_quote_raw                               28347 non-null  str    
 52  minimum_nights                                29682 non-null  float64
 53  maximum_nights                                29682 non-null  float64
 54  minimum_minimum_nights                        29682 non-null  float64
 55  maximum_minimum_nights                        29682 non-null  float64
 56  minimum_maximum_nights                        29682 non-null  float64
 57  maximum_maximum_nights                        29682 non-null  float64
 58  minimum_nights_avg_ntm                        29685 non-null  float64
 59  maximum_nights_avg_ntm                        29685 non-null  float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              29490 non-null  str    
 62  availability_30                               29685 non-null  int64  
 63  availability_60                               29685 non-null  int64  
 64  availability_90                               29685 non-null  int64  
 65  availability_365                              29685 non-null  int64  
 66  calendar_last_scraped                         29685 non-null  str    
 67  number_of_reviews                             29685 non-null  int64  
 68  number_of_reviews_ltm                         29685 non-null  int64  
 69  number_of_reviews_l30d                        29685 non-null  int64  
 70  availability_eoy                              29685 non-null  int64  
 71  number_of_reviews_ly                          29685 non-null  int64  
 72  estimated_occupancy_l365d                     29685 non-null  int64  
 73  estimated_revenue_l365d                       27888 non-null  float64
 74  first_review                                  25957 non-null  str    
 75  last_review                                   25957 non-null  str    
 76  review_scores_rating                          25957 non-null  float64
 77  review_scores_accuracy                        25957 non-null  float64
 78  review_scores_cleanliness                     25957 non-null  float64
 79  review_scores_checkin                         25957 non-null  float64
 80  review_scores_communication                   25957 non-null  float64
 81  review_scores_location                        25957 non-null  float64
 82  review_scores_value                           25957 non-null  float64
 83  license                                       486 non-null    str    
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                29685 non-null  int64  
 86  calculated_host_listings_count_entire_homes   29685 non-null  int64  
 87  calculated_host_listings_count_private_rooms  29685 non-null  int64  
 88  calculated_host_listings_count_shared_rooms   29685 non-null  int64  
 89  reviews_per_month                             25957 non-null  float64

* **`id`**: Identificador único de la publicación. cuanti discreta . int64 

* **`host_name`**: Nombre de pila del anfitrión. Cualitativa nominal. str
* **`hosts_time_as_user_years`**: Años de antigüedad en la plataforma como usuario. Cuantitativa discreta. int64
* **`hosts_time_as_host_years`**: Años de experiencia operando como anfitrión. Cuantitativa discreta. int64
* **`host_is_superhost`**: Etiqueta (verdadero/falso) que indica si el anfitrión tiene la medalla "Superhost". Cualitativa Nominal Dicotomica. str
* **`host_has_profile_pic`**: Indica (verdadero/falso) si el anfitrión tiene subida una foto de perfil. Cualitativa Nominal Dicotomica str
* **`host_identity_verified`**: Indica (verdadero/falso) si el anfitrión validó su documentación oficial. Cualitativa Nominal Dicotomica str
* **`neighbourhood_cleansed`**: Nombre del barrio oficial y validado estandarizadamente. Cualitativa Nominal. str

* **`property_type`**: Tipo arquitectónico o específico de propiedad (ej. Cabaña, Loft, Departamento). Cualitativa Nominal. str
* **`room_type`**: Categoría comercial de alojamiento (Casa entera, Habitación privada o Habitación compartida). Cualitativa Nominal. str
* **`accommodates`**: Capacidad máxima de huéspedes que pueden dormir en la propiedad. Cuantitativa Discreta. int64. Esta limitada a 16 por airbnb
* **`bathrooms`**: Cantidad numérica total de baños. Cuantitativa continua. float64
* **`bedrooms`**: Cantidad total de habitaciones. Cuantitativa discreta. float64
* **`beds`**: Cantidad total de camas físicas disponibles. Cuantitativa discreta. float64
* **`amenities`**: Listado de todos los servicios y comodidades incluidos (Wifi, aire acondicionado, etc.). Cualitativa Nominal. str
* **`price`**: Precio base diario del alquiler en formato texto (suele incluir símbolo de moneda). Cuantitativa Continua. str

* **`minimum_nights`**: Cantidad mínima de noches exigida de forma general para poder reservar. Cuantitativa discreta. float64
* **`maximum_nights`**: Cantidad máxima de noches permitida de forma general. Cuantitativa discreta. float64

* **`has_availability`**: Etiqueta (verdadero/falso) que indica si la propiedad está abierta a recibir huéspedes. Cualitativa Nominal Dicotomica. str

* **`availability_365`**: Cantidad de días disponibles para reservar en los próximos 365 días. Cuantitativa discreta. int64

* **`number_of_reviews_ltm`**: Cantidad de reseñas recibidas exclusivamente en los últimos 12 meses. Cuantitativa discreta. int64

* **`estimated_occupancy_l365d`**: Cálculo estimado de la cantidad de días que la propiedad estuvo ocupada en el último año. Cuantitativa discreta. int64
* **`estimated_revenue_l365d`**: Cálculo estimado de los ingresos económicos brutos generados en el último año. Cuantitativa continua. float64

* **`review_scores_rating`**: Puntaje promedio general del anuncio otorgado por los huéspedes. Cuantitativa Continua. float64

* **`calculated_host_listings_count`**: Cantidad de anuncios totales del anfitrión limitados a esta misma ciudad/región. Cuantitativa discreta. int64

* **`reviews_per_month`**: Frecuencia promedio mensual con la que la propiedad recibe reseñas. Cuantitativa Continua. float64

In [6]:
columnas_tpe = [
    'id', 'host_name', 'hosts_time_as_user_years', 'hosts_time_as_host_years', 
    'host_is_superhost', 'host_has_profile_pic', 'host_identity_verified', 
    'neighbourhood_cleansed', 'property_type', 'room_type', 'accommodates', 
    'bathrooms', 'bedrooms', 'beds', 'amenities', 'price', 'minimum_nights', 
    'maximum_nights', 'has_availability', 'availability_365', 
    'number_of_reviews_ltm', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 
    'review_scores_rating', 'calculated_host_listings_count', 'reviews_per_month'
]

In [8]:
df_copia = df_listings[columnas_tpe]
df_copia.info()

<class 'pandas.DataFrame'>
RangeIndex: 29685 entries, 0 to 29684
Data columns (total 26 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              29685 non-null  int64
 1   host_name                       29685 non-null  str
 2   hosts_time_as_user_years        29685 non-null  int64
 3   hosts_time_as_host_years        29685 non-null  int64
 4   host_is_superhost               29685 non-null  str
 5   host_has_profile_pic            29685 non-null  str
 6   host_identity_verified          29685 non-null  str
 7   neighbourhood_cleansed          29685 non-null  str
 8   property_type                   29685 non-null  str
 9   room_type                       29685 non-null  str
 10  accommodates                    29685 non-null  int64
 11  bathrooms                       26244 non-null  float64
 12  bedrooms                        24500 non-null  float64
 13  beds                            27102 non-null  float64
 14  amenities                       29685 non-null  str
 15  price                           27893 non-null  str
 16  minimum_nights                  29682 non-null  float64
 17  maximum_nights                  29682 non-null  float64
 18  has_availability                29490 non-null  str
 19  availability_365                29685 non-null  int64
 20  number_of_reviews_ltm           29685 non-null  int64
 21  estimated_occupancy_l365d       29685 non-null  int64
 22  estimated_revenue_l365d         27888 non-null  float64
 23  review_scores_rating            25957 non-null  float64
 24  calculated_host_listings_count  29685 non-null  int64
 25  reviews_per_month               25957 non-null  float64
dtypes: float64(8), int64(8), str(10)
memory usage: 5.9 MB

In [9]:
df_copia.describe()

,id,hosts_time_as_user_years,hosts_time_as_host_years,accommodates,bathrooms,bedrooms,beds,minimum_nights,maximum_nights,availability_365,number_of_reviews_ltm,estimated_occupancy_l365d,estimated_revenue_l365d,review_scores_rating,calculated_host_listings_count,reviews_per_month
count,2.968500e+04,29685.000000,29685.000000,29685.000000,26244.000000,24500.000000,27102.000000,29682.000000,29682.000000,29685.000000,29685.000000,29685.000000,2.788800e+04,25957.000000,29685.000000,25957.000000
mean,9.329954e+17,7.506687,5.323362,2.941654,1.244494,1.354612,1.947753,4.951722,563.329897,235.017147,12.602998,74.495873,9.570563e+06,4.780634,15.194240,1.481166
std,5.838355e+17,4.083517,4.046868,1.584278,0.703987,0.914463,1.621595,18.114840,430.722323,116.160445,18.157164,82.642132,2.162264e+07,0.357190,32.782011,1.640487
min,1.150800e+04,0.000000,0.000000,1.000000,0.500000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,0.010000
25%,6.233293e+17,4.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,364.000000,148.000000,1.000000,6.000000,5.360180e+05,4.730000,1.000000,0.370000
50%,1.046350e+18,8.000000,4.000000,2.000000,1.000000,1.000000,1.000000,2.000000,365.000000,264.000000,5.000000,42.000000,4.455030e+06,4.870000,3.000000,0.980000
75%,1.431417e+18,11.000000,8.000000,4.000000,1.000000,1.000000,2.000000,3.000000,1125.000000,343.000000,18.000000,120.000000,1.316291e+07,4.980000,12.000000,2.050000
max,1.717830e+18,17.000000,15.000000,16.000000,22.000000,31.000000,50.000000,730.000000,3659.000000,365.000000,581.000000,255.000000,1.285326e+09,5.000000,208.000000,41.660000

In [19]:
# Muestra una lista con cada variable y su cantidad exacta de nulos
df_copia.isnull().sum()

id                                   0
host_name                            0
hosts_time_as_user_years             0
hosts_time_as_host_years             0
host_is_superhost                    0
host_has_profile_pic                 0
host_identity_verified               0
neighbourhood_cleansed               0
property_type                        0
room_type                            0
accommodates                         0
bathrooms                         3441
bedrooms                          5185
beds                              2583
amenities                            0
price                             1792
minimum_nights                       3
maximum_nights                       3
has_availability                   195
availability_365                     0
number_of_reviews_ltm                0
estimated_occupancy_l365d            0
estimated_revenue_l365d           1797
review_scores_rating              3728
calculated_host_listings_count       0
reviews_per_month                 3728
dtype: int64

In [31]:
# Si tus valores son 't' y 'f':
df_copia['host_is_superhost'] = df_copia['host_is_superhost'].map({'t': True, 'f': False})
df_copia['host_has_profile_pic'] = df_copia['host_has_profile_pic'].map({'t': True, 'f': False})
df_copia['host_identity_verified'] = df_copia['host_identity_verified'].map({'t': True, 'f': False})
df_copia['host_identity_verified'].value_counts()

host_identity_verified
True     29533
False      152
Name: count, dtype: int64

In [53]:
df_copia[df_copia['bathrooms'].isnull()]['bathrooms']

Series([], Name: bathrooms, dtype: float64)

In [52]:
df_copia['bathrooms'] = df_copia['bathrooms'].fillna(df_copia.groupby('accommodates')['bathrooms'].transform('median'))

### 2. Tratamiento de Datos Faltantes (Data Cleaning)

#### 2.1. Imputación de la variable `bathrooms`
Durante el diagnóstico inicial detectamos aproximadamente 3.000 valores nulos en la columna `bathrooms`. Para tratar esta anomalía, definimos la siguiente estrategia:

* **Mecanismo de pérdida (MAR):** Descartamos que los datos falten de forma completamente aleatoria (MCAR). Asumimos un mecanismo *Missing At Random* (MAR), ya que la cantidad de baños esperada está directamente correlacionada con la capacidad máxima de la propiedad (`accommodates`). 
* **Decisión metodológica:** Se descartó la eliminación de filas para no perder el 10% de la muestra. Asimismo, se descartó la imputación global por la media o mediana de toda la columna. En su lugar, aplicamos una **imputación condicional**: reemplazamos los nulos con la mediana de baños del subgrupo de propiedades que comparten la misma capacidad de huéspedes.
* **Efectos sobre la distribución y varianza:** Como advierte la teoría estadística, imputar valores mediante la media o mediana global atenúa artificialmente la variabilidad y las correlaciones porque introduce valores constantes generalizados. Al agrupar por `accommodates` e imputar condicionalmente, logramos rescatar los registros minimizando el impacto sobre la varianza original y preservando la forma de la distribución real de los datos.

In [50]:
# Obtiene los valores únicos y filtra los de menos de 4 caracteres
valores_unicos = df_copia['property_type'].dropna().unique()
nombres_cortos = [nombre for nombre in valores_unicos if len(str(nombre)) < 10]

print(nombres_cortos)

['Tower', 'Tiny home', 'Camper/RV', 'Farm stay', 'Castle', 'Houseboat']

In [57]:
df_copia.groupby('accommodates')['bathrooms'].median()

accommodates
1     1.00
2     1.00
3     1.00
4     1.00
5     1.50
6     2.00
7     2.00
8     2.00
9     2.50
10    3.00
11    2.50
12    4.00
13    3.00
14    4.25
15    5.50
16    5.00
Name: bathrooms, dtype: float64